name: al_motafawiq
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  image_picker: ^1.2.1
  animated_text_kit: ^4.3.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  easy_localization: ^3.0.8
  flutter_gemini: ^3.0.0
  markdown: ^7.3.0
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  groq: ^1.1.1
  shimmer: ^3.0.0
  animate_gradient: ^0.0.4
  animated_background: ^2.0.0
  clay_containers: ^0.3.4
  zo_animated_border: ^1.0.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^7.2.0
  file_picker: ^10.3.8
  video_player: ^2.10.1
  google_generative_ai: ^0.4.7
  dart_openai: ^6.1.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/lottie/
    - .env
